ERROR 2023-08-24 17:01:36,275 django.request Internal Server Error: /api/instance/6611e1ab-d034-4dfc-bd50-0270a51e5870/redis-info/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "./redisinsight/core/views/decorators.py", line 47, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 109, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 144, in _wrapped_view
  File "./redisinsight/core/services/licensing.py", line 325, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 199, in _wrapped_view
  File "./redisinsight/core/views/decorators.py", line 21, in wrapped_view
  File "./redisinsight/monitoring/views.py", line 156, in get_overview_info
  File "./redisinsight/monitoring/views.py", line 119, in _get_cluster_metrics
  File "./redisinsight/monitoring/views.py", line 104, in get_cluster_shards
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 855, in cluster_nodes
    return self.execute_command('CLUSTER NODES')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 555, in execute_command
    return self._execute_command(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 581, in _execute_command
    return self._execute_command_on_nodes(node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 735, in _execute_command_on_nodes
    res[node["name"]] = self.parse_response(connection, command, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 921, in parse_response
    return self.response_callbacks[command_name](response, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/utils.py", line 163, in parse_cluster_nodes
    'cluster-bus-port': int(cluster_port) if cluster_port else 10000 + int(port),
                        ^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '16383,,shard-id=1db7a495008814f010d4f91f9f422d8e4b8b30da'
ERROR 2023-08-24 17:01:43,327 django.request Internal Server Error: /api/instance/6611e1ab-d034-4dfc-bd50-0270a51e5870/get-keys/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "./redisinsight/core/views/decorators.py", line 47, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 109, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 144, in _wrapped_view
  File "./redisinsight/core/services/access_control.py", line 198, in _wrapped_view
  File "./redisinsight/core/services/licensing.py", line 325, in _wrapped_view
  File "./redisinsight/core/services/api_limit.py", line 134, in view_func
  File "./redisinsight/utils/__init__.py", line 199, in _wrapped_view
  File "./redisinsight/core/views/decorators.py", line 21, in wrapped_view
  File "./redisinsight/browser/decorators.py", line 36, in _wrapped_view
  File "./redisinsight/browser/views.py", line 96, in get_keys
  File "./redisinsight/browser/views.py", line 60, in get_total_keys_in_db
  File "./redisinsight/core/services/redis_conn.py", line 737, in get_cluster_node_connections
  File "./redisinsight/core/services/redis_conn.py", line 724, in get_cluster_nodes
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 855, in cluster_nodes
    return self.execute_command('CLUSTER NODES')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 555, in execute_command
    return self._execute_command(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 581, in _execute_command
    return self._execute_command_on_nodes(node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 735, in _execute_command_on_nodes
    res[node["name"]] = self.parse_response(connection, command, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 921, in parse_response
    return self.response_callbacks[command_name](response, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/utils.py", line 163, in parse_cluster_nodes
    'cluster-bus-port': int(cluster_port) if cluster_port else 10000 + int(port),
                        ^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '16380,,shard-id=72f90d37be9cc2b257b03b7000e6b98c4d4e6a62'
ERROR 2023-08-24 17:01:50,181 django.request Internal Server Error: /api/instance/6611e1ab-d034-4dfc-bd50-0270a51e5870/get-keys/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "./redisinsight/core/views/decorators.py", line 47, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 109, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 144, in _wrapped_view
  File "./redisinsight/core/services/access_control.py", line 198, in _wrapped_view
  File "./redisinsight/core/services/licensing.py", line 325, in _wrapped_view
  File "./redisinsight/core/services/api_limit.py", line 134, in view_func
  File "./redisinsight/utils/__init__.py", line 199, in _wrapped_view
  File "./redisinsight/core/views/decorators.py", line 21, in wrapped_view
  File "./redisinsight/browser/decorators.py", line 36, in _wrapped_view
  File "./redisinsight/browser/views.py", line 96, in get_keys
  File "./redisinsight/browser/views.py", line 60, in get_total_keys_in_db
  File "./redisinsight/core/services/redis_conn.py", line 737, in get_cluster_node_connections
  File "./redisinsight/core/services/redis_conn.py", line 724, in get_cluster_nodes
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 855, in cluster_nodes
    return self.execute_command('CLUSTER NODES')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 555, in execute_command
    return self._execute_command(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 581, in _execute_command
    return self._execute_command_on_nodes(node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 735, in _execute_command_on_nodes
    res[node["name"]] = self.parse_response(connection, command, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 921, in parse_response
    return self.response_callbacks[command_name](response, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/utils.py", line 163, in parse_cluster_nodes
    'cluster-bus-port': int(cluster_port) if cluster_port else 10000 + int(port),
                        ^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '16379,,shard-id=2cfd46507ccce06f9a66ae7f720750458731dfb8'
ERROR 2023-08-24 17:01:50,529 django.request Internal Server Error: /api/instance/6611e1ab-d034-4dfc-bd50-0270a51e5870/get-keys/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "./redisinsight/core/views/decorators.py", line 47, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 109, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 144, in _wrapped_view
  File "./redisinsight/core/services/access_control.py", line 198, in _wrapped_view
  File "./redisinsight/core/services/licensing.py", line 325, in _wrapped_view
  File "./redisinsight/core/services/api_limit.py", line 134, in view_func
  File "./redisinsight/utils/__init__.py", line 199, in _wrapped_view
  File "./redisinsight/core/views/decorators.py", line 21, in wrapped_view
  File "./redisinsight/browser/decorators.py", line 36, in _wrapped_view
  File "./redisinsight/browser/views.py", line 96, in get_keys
  File "./redisinsight/browser/views.py", line 60, in get_total_keys_in_db
  File "./redisinsight/core/services/redis_conn.py", line 737, in get_cluster_node_connections
  File "./redisinsight/core/services/redis_conn.py", line 724, in get_cluster_nodes
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 855, in cluster_nodes
    return self.execute_command('CLUSTER NODES')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 555, in execute_command
    return self._execute_command(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 581, in _execute_command
    return self._execute_command_on_nodes(node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 735, in _execute_command_on_nodes
    res[node["name"]] = self.parse_response(connection, command, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 921, in parse_response
    return self.response_callbacks[command_name](response, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/utils.py", line 163, in parse_cluster_nodes
    'cluster-bus-port': int(cluster_port) if cluster_port else 10000 + int(port),
                        ^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '16383,,shard-id=1db7a495008814f010d4f91f9f422d8e4b8b30da'
ERROR 2023-08-24 17:01:50,772 django.request Internal Server Error: /api/instance/6611e1ab-d034-4dfc-bd50-0270a51e5870/get-keys/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "./redisinsight/core/views/decorators.py", line 47, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 109, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 144, in _wrapped_view
  File "./redisinsight/core/services/access_control.py", line 198, in _wrapped_view
  File "./redisinsight/core/services/licensing.py", line 325, in _wrapped_view
  File "./redisinsight/core/services/api_limit.py", line 134, in view_func
  File "./redisinsight/utils/__init__.py", line 199, in _wrapped_view
  File "./redisinsight/core/views/decorators.py", line 21, in wrapped_view
  File "./redisinsight/browser/decorators.py", line 36, in _wrapped_view
  File "./redisinsight/browser/views.py", line 96, in get_keys
  File "./redisinsight/browser/views.py", line 60, in get_total_keys_in_db
  File "./redisinsight/core/services/redis_conn.py", line 737, in get_cluster_node_connections
  File "./redisinsight/core/services/redis_conn.py", line 724, in get_cluster_nodes
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 855, in cluster_nodes
    return self.execute_command('CLUSTER NODES')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 555, in execute_command
    return self._execute_command(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 581, in _execute_command
    return self._execute_command_on_nodes(node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 735, in _execute_command_on_nodes
    res[node["name"]] = self.parse_response(connection, command, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 921, in parse_response
    return self.response_callbacks[command_name](response, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/utils.py", line 163, in parse_cluster_nodes
    'cluster-bus-port': int(cluster_port) if cluster_port else 10000 + int(port),
                        ^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '16380,,shard-id=72f90d37be9cc2b257b03b7000e6b98c4d4e6a62'
ERROR 2023-08-24 17:01:50,922 django.request Internal Server Error: /api/instance/6611e1ab-d034-4dfc-bd50-0270a51e5870/get-keys/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "./redisinsight/core/views/decorators.py", line 47, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 109, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 144, in _wrapped_view
  File "./redisinsight/core/services/access_control.py", line 198, in _wrapped_view
  File "./redisinsight/core/services/licensing.py", line 325, in _wrapped_view
  File "./redisinsight/core/services/api_limit.py", line 134, in view_func
  File "./redisinsight/utils/__init__.py", line 199, in _wrapped_view
  File "./redisinsight/core/views/decorators.py", line 21, in wrapped_view
  File "./redisinsight/browser/decorators.py", line 36, in _wrapped_view
  File "./redisinsight/browser/views.py", line 96, in get_keys
  File "./redisinsight/browser/views.py", line 60, in get_total_keys_in_db
  File "./redisinsight/core/services/redis_conn.py", line 737, in get_cluster_node_connections
  File "./redisinsight/core/services/redis_conn.py", line 724, in get_cluster_nodes
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 855, in cluster_nodes
    return self.execute_command('CLUSTER NODES')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 555, in execute_command
    return self._execute_command(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 581, in _execute_command
    return self._execute_command_on_nodes(node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 735, in _execute_command_on_nodes
    res[node["name"]] = self.parse_response(connection, command, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 921, in parse_response
    return self.response_callbacks[command_name](response, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/utils.py", line 163, in parse_cluster_nodes
    'cluster-bus-port': int(cluster_port) if cluster_port else 10000 + int(port),
                        ^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '16383,,shard-id=1db7a495008814f010d4f91f9f422d8e4b8b30da'
ERROR 2023-08-24 17:01:51,109 django.request Internal Server Error: /api/instance/6611e1ab-d034-4dfc-bd50-0270a51e5870/get-keys/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "./redisinsight/core/views/decorators.py", line 47, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 109, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 144, in _wrapped_view
  File "./redisinsight/core/services/access_control.py", line 198, in _wrapped_view
  File "./redisinsight/core/services/licensing.py", line 325, in _wrapped_view
  File "./redisinsight/core/services/api_limit.py", line 134, in view_func
  File "./redisinsight/utils/__init__.py", line 199, in _wrapped_view
  File "./redisinsight/core/views/decorators.py", line 21, in wrapped_view
  File "./redisinsight/browser/decorators.py", line 36, in _wrapped_view
  File "./redisinsight/browser/views.py", line 96, in get_keys
  File "./redisinsight/browser/views.py", line 60, in get_total_keys_in_db
  File "./redisinsight/core/services/redis_conn.py", line 737, in get_cluster_node_connections
  File "./redisinsight/core/services/redis_conn.py", line 724, in get_cluster_nodes
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 855, in cluster_nodes
    return self.execute_command('CLUSTER NODES')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 555, in execute_command
    return self._execute_command(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 581, in _execute_command
    return self._execute_command_on_nodes(node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 735, in _execute_command_on_nodes
    res[node["name"]] = self.parse_response(connection, command, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 921, in parse_response
    return self.response_callbacks[command_name](response, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/utils.py", line 163, in parse_cluster_nodes
    'cluster-bus-port': int(cluster_port) if cluster_port else 10000 + int(port),
                        ^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '16380,,shard-id=72f90d37be9cc2b257b03b7000e6b98c4d4e6a62'
ERROR 2023-08-24 17:01:51,282 django.request Internal Server Error: /api/instance/6611e1ab-d034-4dfc-bd50-0270a51e5870/get-keys/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "./redisinsight/core/views/decorators.py", line 47, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 109, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 144, in _wrapped_view
  File "./redisinsight/core/services/access_control.py", line 198, in _wrapped_view
  File "./redisinsight/core/services/licensing.py", line 325, in _wrapped_view
  File "./redisinsight/core/services/api_limit.py", line 134, in view_func
  File "./redisinsight/utils/__init__.py", line 199, in _wrapped_view
  File "./redisinsight/core/views/decorators.py", line 21, in wrapped_view
  File "./redisinsight/browser/decorators.py", line 36, in _wrapped_view
  File "./redisinsight/browser/views.py", line 96, in get_keys
  File "./redisinsight/browser/views.py", line 60, in get_total_keys_in_db
  File "./redisinsight/core/services/redis_conn.py", line 737, in get_cluster_node_connections
  File "./redisinsight/core/services/redis_conn.py", line 724, in get_cluster_nodes
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 855, in cluster_nodes
    return self.execute_command('CLUSTER NODES')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 555, in execute_command
    return self._execute_command(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 581, in _execute_command
    return self._execute_command_on_nodes(node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 735, in _execute_command_on_nodes
    res[node["name"]] = self.parse_response(connection, command, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 921, in parse_response
    return self.response_callbacks[command_name](response, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/utils.py", line 163, in parse_cluster_nodes
    'cluster-bus-port': int(cluster_port) if cluster_port else 10000 + int(port),
                        ^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '16382,,shard-id=1db7a495008814f010d4f91f9f422d8e4b8b30da'
ERROR 2023-08-24 17:01:51,687 django.request Internal Server Error: /api/instance/6611e1ab-d034-4dfc-bd50-0270a51e5870/get-keys/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "./redisinsight/core/views/decorators.py", line 47, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 109, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 144, in _wrapped_view
  File "./redisinsight/core/services/access_control.py", line 198, in _wrapped_view
  File "./redisinsight/core/services/licensing.py", line 325, in _wrapped_view
  File "./redisinsight/core/services/api_limit.py", line 134, in view_func
  File "./redisinsight/utils/__init__.py", line 199, in _wrapped_view
  File "./redisinsight/core/views/decorators.py", line 21, in wrapped_view
  File "./redisinsight/browser/decorators.py", line 36, in _wrapped_view
  File "./redisinsight/browser/views.py", line 96, in get_keys
  File "./redisinsight/browser/views.py", line 60, in get_total_keys_in_db
  File "./redisinsight/core/services/redis_conn.py", line 737, in get_cluster_node_connections
  File "./redisinsight/core/services/redis_conn.py", line 724, in get_cluster_nodes
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 855, in cluster_nodes
    return self.execute_command('CLUSTER NODES')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 555, in execute_command
    return self._execute_command(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 581, in _execute_command
    return self._execute_command_on_nodes(node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 735, in _execute_command_on_nodes
    res[node["name"]] = self.parse_response(connection, command, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 921, in parse_response
    return self.response_callbacks[command_name](response, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/utils.py", line 163, in parse_cluster_nodes
    'cluster-bus-port': int(cluster_port) if cluster_port else 10000 + int(port),
                        ^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '16379,,shard-id=2cfd46507ccce06f9a66ae7f720750458731dfb8'
ERROR 2023-08-24 17:01:51,879 django.request Internal Server Error: /api/instance/6611e1ab-d034-4dfc-bd50-0270a51e5870/get-keys/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "./redisinsight/core/views/decorators.py", line 47, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 109, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 144, in _wrapped_view
  File "./redisinsight/core/services/access_control.py", line 198, in _wrapped_view
  File "./redisinsight/core/services/licensing.py", line 325, in _wrapped_view
  File "./redisinsight/core/services/api_limit.py", line 134, in view_func
  File "./redisinsight/utils/__init__.py", line 199, in _wrapped_view
  File "./redisinsight/core/views/decorators.py", line 21, in wrapped_view
  File "./redisinsight/browser/decorators.py", line 36, in _wrapped_view
  File "./redisinsight/browser/views.py", line 96, in get_keys
  File "./redisinsight/browser/views.py", line 60, in get_total_keys_in_db
  File "./redisinsight/core/services/redis_conn.py", line 737, in get_cluster_node_connections
  File "./redisinsight/core/services/redis_conn.py", line 724, in get_cluster_nodes
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 855, in cluster_nodes
    return self.execute_command('CLUSTER NODES')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 555, in execute_command
    return self._execute_command(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 581, in _execute_command
    return self._execute_command_on_nodes(node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 735, in _execute_command_on_nodes
    res[node["name"]] = self.parse_response(connection, command, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 921, in parse_response
    return self.response_callbacks[command_name](response, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/utils.py", line 163, in parse_cluster_nodes
    'cluster-bus-port': int(cluster_port) if cluster_port else 10000 + int(port),
                        ^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '16380,,shard-id=72f90d37be9cc2b257b03b7000e6b98c4d4e6a62'
ERROR 2023-08-24 17:01:52,041 django.request Internal Server Error: /api/instance/6611e1ab-d034-4dfc-bd50-0270a51e5870/get-keys/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "./redisinsight/core/views/decorators.py", line 47, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 109, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 144, in _wrapped_view
  File "./redisinsight/core/services/access_control.py", line 198, in _wrapped_view
  File "./redisinsight/core/services/licensing.py", line 325, in _wrapped_view
  File "./redisinsight/core/services/api_limit.py", line 134, in view_func
  File "./redisinsight/utils/__init__.py", line 199, in _wrapped_view
  File "./redisinsight/core/views/decorators.py", line 21, in wrapped_view
  File "./redisinsight/browser/decorators.py", line 36, in _wrapped_view
  File "./redisinsight/browser/views.py", line 96, in get_keys
  File "./redisinsight/browser/views.py", line 60, in get_total_keys_in_db
  File "./redisinsight/core/services/redis_conn.py", line 737, in get_cluster_node_connections
  File "./redisinsight/core/services/redis_conn.py", line 724, in get_cluster_nodes
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 855, in cluster_nodes
    return self.execute_command('CLUSTER NODES')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 555, in execute_command
    return self._execute_command(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 581, in _execute_command
    return self._execute_command_on_nodes(node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 735, in _execute_command_on_nodes
    res[node["name"]] = self.parse_response(connection, command, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 921, in parse_response
    return self.response_callbacks[command_name](response, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/utils.py", line 163, in parse_cluster_nodes
    'cluster-bus-port': int(cluster_port) if cluster_port else 10000 + int(port),
                        ^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '16380,,shard-id=72f90d37be9cc2b257b03b7000e6b98c4d4e6a62'
ERROR 2023-08-24 17:01:52,196 django.request Internal Server Error: /api/instance/6611e1ab-d034-4dfc-bd50-0270a51e5870/get-keys/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "./redisinsight/core/views/decorators.py", line 47, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 109, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 144, in _wrapped_view
  File "./redisinsight/core/services/access_control.py", line 198, in _wrapped_view
  File "./redisinsight/core/services/licensing.py", line 325, in _wrapped_view
  File "./redisinsight/core/services/api_limit.py", line 134, in view_func
  File "./redisinsight/utils/__init__.py", line 199, in _wrapped_view
  File "./redisinsight/core/views/decorators.py", line 21, in wrapped_view
  File "./redisinsight/browser/decorators.py", line 36, in _wrapped_view
  File "./redisinsight/browser/views.py", line 96, in get_keys
  File "./redisinsight/browser/views.py", line 60, in get_total_keys_in_db
  File "./redisinsight/core/services/redis_conn.py", line 737, in get_cluster_node_connections
  File "./redisinsight/core/services/redis_conn.py", line 724, in get_cluster_nodes
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 855, in cluster_nodes
    return self.execute_command('CLUSTER NODES')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 555, in execute_command
    return self._execute_command(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 581, in _execute_command
    return self._execute_command_on_nodes(node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 735, in _execute_command_on_nodes
    res[node["name"]] = self.parse_response(connection, command, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 921, in parse_response
    return self.response_callbacks[command_name](response, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/utils.py", line 163, in parse_cluster_nodes
    'cluster-bus-port': int(cluster_port) if cluster_port else 10000 + int(port),
                        ^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '16383,,shard-id=1db7a495008814f010d4f91f9f422d8e4b8b30da'
ERROR 2023-08-24 17:01:52,392 django.request Internal Server Error: /api/instance/6611e1ab-d034-4dfc-bd50-0270a51e5870/get-keys/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "./redisinsight/core/views/decorators.py", line 47, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 109, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 144, in _wrapped_view
  File "./redisinsight/core/services/access_control.py", line 198, in _wrapped_view
  File "./redisinsight/core/services/licensing.py", line 325, in _wrapped_view
  File "./redisinsight/core/services/api_limit.py", line 134, in view_func
  File "./redisinsight/utils/__init__.py", line 199, in _wrapped_view
  File "./redisinsight/core/views/decorators.py", line 21, in wrapped_view
  File "./redisinsight/browser/decorators.py", line 36, in _wrapped_view
  File "./redisinsight/browser/views.py", line 96, in get_keys
  File "./redisinsight/browser/views.py", line 60, in get_total_keys_in_db
  File "./redisinsight/core/services/redis_conn.py", line 737, in get_cluster_node_connections
  File "./redisinsight/core/services/redis_conn.py", line 724, in get_cluster_nodes
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 855, in cluster_nodes
    return self.execute_command('CLUSTER NODES')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 555, in execute_command
    return self._execute_command(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 581, in _execute_command
    return self._execute_command_on_nodes(node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 735, in _execute_command_on_nodes
    res[node["name"]] = self.parse_response(connection, command, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 921, in parse_response
    return self.response_callbacks[command_name](response, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/utils.py", line 163, in parse_cluster_nodes
    'cluster-bus-port': int(cluster_port) if cluster_port else 10000 + int(port),
                        ^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '16383,,shard-id=1db7a495008814f010d4f91f9f422d8e4b8b30da'
ERROR 2023-08-24 17:01:52,692 django.request Internal Server Error: /api/instance/6611e1ab-d034-4dfc-bd50-0270a51e5870/get-keys/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "./redisinsight/core/views/decorators.py", line 47, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 109, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 144, in _wrapped_view
  File "./redisinsight/core/services/access_control.py", line 198, in _wrapped_view
  File "./redisinsight/core/services/licensing.py", line 325, in _wrapped_view
  File "./redisinsight/core/services/api_limit.py", line 134, in view_func
  File "./redisinsight/utils/__init__.py", line 199, in _wrapped_view
  File "./redisinsight/core/views/decorators.py", line 21, in wrapped_view
  File "./redisinsight/browser/decorators.py", line 36, in _wrapped_view
  File "./redisinsight/browser/views.py", line 96, in get_keys
  File "./redisinsight/browser/views.py", line 60, in get_total_keys_in_db
  File "./redisinsight/core/services/redis_conn.py", line 737, in get_cluster_node_connections
  File "./redisinsight/core/services/redis_conn.py", line 724, in get_cluster_nodes
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 855, in cluster_nodes
    return self.execute_command('CLUSTER NODES')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 555, in execute_command
    return self._execute_command(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 581, in _execute_command
    return self._execute_command_on_nodes(node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 735, in _execute_command_on_nodes
    res[node["name"]] = self.parse_response(connection, command, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 921, in parse_response
    return self.response_callbacks[command_name](response, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/utils.py", line 163, in parse_cluster_nodes
    'cluster-bus-port': int(cluster_port) if cluster_port else 10000 + int(port),
                        ^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '16382,,shard-id=1db7a495008814f010d4f91f9f422d8e4b8b30da'
ERROR 2023-08-24 17:01:53,155 django.request Internal Server Error: /api/instance/6611e1ab-d034-4dfc-bd50-0270a51e5870/get-keys/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "./redisinsight/core/views/decorators.py", line 47, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 109, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 144, in _wrapped_view
  File "./redisinsight/core/services/access_control.py", line 198, in _wrapped_view
  File "./redisinsight/core/services/licensing.py", line 325, in _wrapped_view
  File "./redisinsight/core/services/api_limit.py", line 134, in view_func
  File "./redisinsight/utils/__init__.py", line 199, in _wrapped_view
  File "./redisinsight/core/views/decorators.py", line 21, in wrapped_view
  File "./redisinsight/browser/decorators.py", line 36, in _wrapped_view
  File "./redisinsight/browser/views.py", line 96, in get_keys
  File "./redisinsight/browser/views.py", line 60, in get_total_keys_in_db
  File "./redisinsight/core/services/redis_conn.py", line 737, in get_cluster_node_connections
  File "./redisinsight/core/services/redis_conn.py", line 724, in get_cluster_nodes
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 855, in cluster_nodes
    return self.execute_command('CLUSTER NODES')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 555, in execute_command
    return self._execute_command(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 581, in _execute_command
    return self._execute_command_on_nodes(node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 735, in _execute_command_on_nodes
    res[node["name"]] = self.parse_response(connection, command, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 921, in parse_response
    return self.response_callbacks[command_name](response, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/utils.py", line 163, in parse_cluster_nodes
    'cluster-bus-port': int(cluster_port) if cluster_port else 10000 + int(port),
                        ^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '16380,,shard-id=72f90d37be9cc2b257b03b7000e6b98c4d4e6a62'
ERROR 2023-08-24 17:01:58,399 django.request Internal Server Error: /api/instance/6611e1ab-d034-4dfc-bd50-0270a51e5870/get-keys/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "./redisinsight/core/views/decorators.py", line 47, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 109, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 144, in _wrapped_view
  File "./redisinsight/core/services/access_control.py", line 198, in _wrapped_view
  File "./redisinsight/core/services/licensing.py", line 325, in _wrapped_view
  File "./redisinsight/core/services/api_limit.py", line 134, in view_func
  File "./redisinsight/utils/__init__.py", line 199, in _wrapped_view
  File "./redisinsight/core/views/decorators.py", line 21, in wrapped_view
  File "./redisinsight/browser/decorators.py", line 36, in _wrapped_view
  File "./redisinsight/browser/views.py", line 96, in get_keys
  File "./redisinsight/browser/views.py", line 60, in get_total_keys_in_db
  File "./redisinsight/core/services/redis_conn.py", line 737, in get_cluster_node_connections
  File "./redisinsight/core/services/redis_conn.py", line 724, in get_cluster_nodes
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 855, in cluster_nodes
    return self.execute_command('CLUSTER NODES')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 555, in execute_command
    return self._execute_command(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 581, in _execute_command
    return self._execute_command_on_nodes(node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 735, in _execute_command_on_nodes
    res[node["name"]] = self.parse_response(connection, command, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 921, in parse_response
    return self.response_callbacks[command_name](response, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/utils.py", line 163, in parse_cluster_nodes
    'cluster-bus-port': int(cluster_port) if cluster_port else 10000 + int(port),
                        ^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '16380,,shard-id=72f90d37be9cc2b257b03b7000e6b98c4d4e6a62'
ERROR 2023-08-24 17:02:01,482 django.request Internal Server Error: /api/instance/6611e1ab-d034-4dfc-bd50-0270a51e5870/get-keys/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "./redisinsight/core/views/decorators.py", line 47, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 109, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 144, in _wrapped_view
  File "./redisinsight/core/services/access_control.py", line 198, in _wrapped_view
  File "./redisinsight/core/services/licensing.py", line 325, in _wrapped_view
  File "./redisinsight/core/services/api_limit.py", line 134, in view_func
  File "./redisinsight/utils/__init__.py", line 199, in _wrapped_view
  File "./redisinsight/core/views/decorators.py", line 21, in wrapped_view
  File "./redisinsight/browser/decorators.py", line 36, in _wrapped_view
  File "./redisinsight/browser/views.py", line 96, in get_keys
  File "./redisinsight/browser/views.py", line 60, in get_total_keys_in_db
  File "./redisinsight/core/services/redis_conn.py", line 737, in get_cluster_node_connections
  File "./redisinsight/core/services/redis_conn.py", line 724, in get_cluster_nodes
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 855, in cluster_nodes
    return self.execute_command('CLUSTER NODES')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 555, in execute_command
    return self._execute_command(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 581, in _execute_command
    return self._execute_command_on_nodes(node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 735, in _execute_command_on_nodes
    res[node["name"]] = self.parse_response(connection, command, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 921, in parse_response
    return self.response_callbacks[command_name](response, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/utils.py", line 163, in parse_cluster_nodes
    'cluster-bus-port': int(cluster_port) if cluster_port else 10000 + int(port),
                        ^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '16379,,shard-id=2cfd46507ccce06f9a66ae7f720750458731dfb8'
ERROR 2023-08-24 17:02:13,893 django.request Internal Server Error: /api/instance/6611e1ab-d034-4dfc-bd50-0270a51e5870/redis-info/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "./redisinsight/core/views/decorators.py", line 47, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 109, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 144, in _wrapped_view
  File "./redisinsight/core/services/licensing.py", line 325, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 199, in _wrapped_view
  File "./redisinsight/core/views/decorators.py", line 21, in wrapped_view
  File "./redisinsight/monitoring/views.py", line 156, in get_overview_info
  File "./redisinsight/monitoring/views.py", line 119, in _get_cluster_metrics
  File "./redisinsight/monitoring/views.py", line 104, in get_cluster_shards
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 855, in cluster_nodes
    return self.execute_command('CLUSTER NODES')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 555, in execute_command
    return self._execute_command(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 581, in _execute_command
    return self._execute_command_on_nodes(node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 735, in _execute_command_on_nodes
    res[node["name"]] = self.parse_response(connection, command, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 921, in parse_response
    return self.response_callbacks[command_name](response, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/utils.py", line 163, in parse_cluster_nodes
    'cluster-bus-port': int(cluster_port) if cluster_port else 10000 + int(port),
                        ^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '16380,,shard-id=72f90d37be9cc2b257b03b7000e6b98c4d4e6a62'
ERROR 2023-08-24 17:02:15,655 django.request Internal Server Error: /api/instance/6611e1ab-d034-4dfc-bd50-0270a51e5870/get-keys/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "./redisinsight/core/views/decorators.py", line 47, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 109, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 144, in _wrapped_view
  File "./redisinsight/core/services/access_control.py", line 198, in _wrapped_view
  File "./redisinsight/core/services/licensing.py", line 325, in _wrapped_view
  File "./redisinsight/core/services/api_limit.py", line 134, in view_func
  File "./redisinsight/utils/__init__.py", line 199, in _wrapped_view
  File "./redisinsight/core/views/decorators.py", line 21, in wrapped_view
  File "./redisinsight/browser/decorators.py", line 36, in _wrapped_view
  File "./redisinsight/browser/views.py", line 96, in get_keys
  File "./redisinsight/browser/views.py", line 60, in get_total_keys_in_db
  File "./redisinsight/core/services/redis_conn.py", line 737, in get_cluster_node_connections
  File "./redisinsight/core/services/redis_conn.py", line 724, in get_cluster_nodes
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 855, in cluster_nodes
    return self.execute_command('CLUSTER NODES')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 555, in execute_command
    return self._execute_command(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 581, in _execute_command
    return self._execute_command_on_nodes(node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 735, in _execute_command_on_nodes
    res[node["name"]] = self.parse_response(connection, command, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 921, in parse_response
    return self.response_callbacks[command_name](response, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/utils.py", line 163, in parse_cluster_nodes
    'cluster-bus-port': int(cluster_port) if cluster_port else 10000 + int(port),
                        ^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '16380,,shard-id=72f90d37be9cc2b257b03b7000e6b98c4d4e6a62'
WARNING 2023-08-24 17:03:22,443 django.request Bad Request: /api/instance/
ERROR 2023-08-24 17:03:31,615 django.request Internal Server Error: /api/instance/d7a4bf4e-2121-4660-b16b-ae11ef79aa79/redis-info/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "./redisinsight/core/views/decorators.py", line 47, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 109, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 144, in _wrapped_view
  File "./redisinsight/core/services/licensing.py", line 325, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 199, in _wrapped_view
  File "./redisinsight/core/views/decorators.py", line 21, in wrapped_view
  File "./redisinsight/monitoring/views.py", line 156, in get_overview_info
  File "./redisinsight/monitoring/views.py", line 119, in _get_cluster_metrics
  File "./redisinsight/monitoring/views.py", line 104, in get_cluster_shards
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 855, in cluster_nodes
    return self.execute_command('CLUSTER NODES')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 555, in execute_command
    return self._execute_command(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 581, in _execute_command
    return self._execute_command_on_nodes(node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 735, in _execute_command_on_nodes
    res[node["name"]] = self.parse_response(connection, command, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 921, in parse_response
    return self.response_callbacks[command_name](response, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/utils.py", line 163, in parse_cluster_nodes
    'cluster-bus-port': int(cluster_port) if cluster_port else 10000 + int(port),
                        ^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '16383,,shard-id=1db7a495008814f010d4f91f9f422d8e4b8b30da'
ERROR 2023-08-24 17:03:34,214 django.request Internal Server Error: /api/instance/d7a4bf4e-2121-4660-b16b-ae11ef79aa79/get-keys/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "./redisinsight/core/views/decorators.py", line 47, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 109, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 144, in _wrapped_view
  File "./redisinsight/core/services/access_control.py", line 198, in _wrapped_view
  File "./redisinsight/core/services/licensing.py", line 325, in _wrapped_view
  File "./redisinsight/core/services/api_limit.py", line 134, in view_func
  File "./redisinsight/utils/__init__.py", line 199, in _wrapped_view
  File "./redisinsight/core/views/decorators.py", line 21, in wrapped_view
  File "./redisinsight/browser/decorators.py", line 36, in _wrapped_view
  File "./redisinsight/browser/views.py", line 96, in get_keys
  File "./redisinsight/browser/views.py", line 60, in get_total_keys_in_db
  File "./redisinsight/core/services/redis_conn.py", line 737, in get_cluster_node_connections
  File "./redisinsight/core/services/redis_conn.py", line 724, in get_cluster_nodes
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 855, in cluster_nodes
    return self.execute_command('CLUSTER NODES')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 555, in execute_command
    return self._execute_command(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 581, in _execute_command
    return self._execute_command_on_nodes(node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 735, in _execute_command_on_nodes
    res[node["name"]] = self.parse_response(connection, command, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 921, in parse_response
    return self.response_callbacks[command_name](response, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/utils.py", line 163, in parse_cluster_nodes
    'cluster-bus-port': int(cluster_port) if cluster_port else 10000 + int(port),
                        ^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '16380,,shard-id=72f90d37be9cc2b257b03b7000e6b98c4d4e6a62'
WARNING 2023-08-24 17:03:37,092 django.request Bad Request: /api/instance/d7a4bf4e-2121-4660-b16b-ae11ef79aa79/redisgraph/check-module-loaded/
ERROR 2023-08-24 17:03:37,245 django.request Internal Server Error: /api/instance/d7a4bf4e-2121-4660-b16b-ae11ef79aa79/redisgraph/find-keys/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "./redisinsight/core/views/decorators.py", line 47, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 109, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 144, in _wrapped_view
  File "./redisinsight/core/services/licensing.py", line 325, in _wrapped_view
  File "./redisinsight/core/services/access_control.py", line 198, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 199, in _wrapped_view
  File "./redisinsight/core/views/decorators.py", line 21, in wrapped_view
  File "./redisinsight/redisgraph/decorators.py", line 34, in _wrapped_view
  File "./redisinsight/redisgraph/views/__init__.py", line 193, in find_keys
  File "./redisinsight/redisgraph/services/__init__.py", line 277, in find_keys_graph
  File "./redisinsight/core/services/redis_conn.py", line 724, in get_cluster_nodes
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 855, in cluster_nodes
    return self.execute_command('CLUSTER NODES')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 555, in execute_command
    return self._execute_command(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 581, in _execute_command
    return self._execute_command_on_nodes(node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 735, in _execute_command_on_nodes
    res[node["name"]] = self.parse_response(connection, command, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 921, in parse_response
    return self.response_callbacks[command_name](response, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/utils.py", line 163, in parse_cluster_nodes
    'cluster-bus-port': int(cluster_port) if cluster_port else 10000 + int(port),
                        ^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '16380,,shard-id=72f90d37be9cc2b257b03b7000e6b98c4d4e6a62'
ERROR 2023-08-24 17:03:38,325 django.request Internal Server Error: /api/instance/d7a4bf4e-2121-4660-b16b-ae11ef79aa79/get-keys/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "./redisinsight/core/views/decorators.py", line 47, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 109, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 144, in _wrapped_view
  File "./redisinsight/core/services/access_control.py", line 198, in _wrapped_view
  File "./redisinsight/core/services/licensing.py", line 325, in _wrapped_view
  File "./redisinsight/core/services/api_limit.py", line 134, in view_func
  File "./redisinsight/utils/__init__.py", line 199, in _wrapped_view
  File "./redisinsight/core/views/decorators.py", line 21, in wrapped_view
  File "./redisinsight/browser/decorators.py", line 36, in _wrapped_view
  File "./redisinsight/browser/views.py", line 96, in get_keys
  File "./redisinsight/browser/views.py", line 60, in get_total_keys_in_db
  File "./redisinsight/core/services/redis_conn.py", line 737, in get_cluster_node_connections
  File "./redisinsight/core/services/redis_conn.py", line 724, in get_cluster_nodes
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 855, in cluster_nodes
    return self.execute_command('CLUSTER NODES')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 555, in execute_command
    return self._execute_command(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 581, in _execute_command
    return self._execute_command_on_nodes(node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 735, in _execute_command_on_nodes
    res[node["name"]] = self.parse_response(connection, command, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 921, in parse_response
    return self.response_callbacks[command_name](response, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/utils.py", line 163, in parse_cluster_nodes
    'cluster-bus-port': int(cluster_port) if cluster_port else 10000 + int(port),
                        ^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '16380,,shard-id=72f90d37be9cc2b257b03b7000e6b98c4d4e6a62'
WARNING 2023-08-24 17:03:40,527 django.request Bad Request: /api/instance/d7a4bf4e-2121-4660-b16b-ae11ef79aa79/redisgraph/check-module-loaded/
ERROR 2023-08-24 17:03:40,578 django.request Internal Server Error: /api/instance/d7a4bf4e-2121-4660-b16b-ae11ef79aa79/redisgraph/find-keys/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "./redisinsight/core/views/decorators.py", line 47, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 109, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 144, in _wrapped_view
  File "./redisinsight/core/services/licensing.py", line 325, in _wrapped_view
  File "./redisinsight/core/services/access_control.py", line 198, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 199, in _wrapped_view
  File "./redisinsight/core/views/decorators.py", line 21, in wrapped_view
  File "./redisinsight/redisgraph/decorators.py", line 34, in _wrapped_view
  File "./redisinsight/redisgraph/views/__init__.py", line 193, in find_keys
  File "./redisinsight/redisgraph/services/__init__.py", line 277, in find_keys_graph
  File "./redisinsight/core/services/redis_conn.py", line 724, in get_cluster_nodes
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 855, in cluster_nodes
    return self.execute_command('CLUSTER NODES')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 555, in execute_command
    return self._execute_command(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 581, in _execute_command
    return self._execute_command_on_nodes(node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 735, in _execute_command_on_nodes
    res[node["name"]] = self.parse_response(connection, command, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 921, in parse_response
    return self.response_callbacks[command_name](response, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/utils.py", line 163, in parse_cluster_nodes
    'cluster-bus-port': int(cluster_port) if cluster_port else 10000 + int(port),
                        ^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '16380,,shard-id=72f90d37be9cc2b257b03b7000e6b98c4d4e6a62'
ERROR 2023-08-24 17:03:46,198 django.request Internal Server Error: /api/instance/d7a4bf4e-2121-4660-b16b-ae11ef79aa79/get-keys/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "./redisinsight/core/views/decorators.py", line 47, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 109, in _wrapped_view
  File "./redisinsight/utils/__init__.py", line 144, in _wrapped_view
  File "./redisinsight/core/services/access_control.py", line 198, in _wrapped_view
  File "./redisinsight/core/services/licensing.py", line 325, in _wrapped_view
  File "./redisinsight/core/services/api_limit.py", line 134, in view_func
  File "./redisinsight/utils/__init__.py", line 199, in _wrapped_view
  File "./redisinsight/core/views/decorators.py", line 21, in wrapped_view
  File "./redisinsight/browser/decorators.py", line 36, in _wrapped_view
  File "./redisinsight/browser/views.py", line 96, in get_keys
  File "./redisinsight/browser/views.py", line 60, in get_total_keys_in_db
  File "./redisinsight/core/services/redis_conn.py", line 737, in get_cluster_node_connections
  File "./redisinsight/core/services/redis_conn.py", line 724, in get_cluster_nodes
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 855, in cluster_nodes
    return self.execute_command('CLUSTER NODES')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 555, in execute_command
    return self._execute_command(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 581, in _execute_command
    return self._execute_command_on_nodes(node, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/client.py", line 735, in _execute_command_on_nodes
    res[node["name"]] = self.parse_response(connection, command, **kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 921, in parse_response
    return self.response_callbacks[command_name](response, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/rediscluster/utils.py", line 163, in parse_cluster_nodes
    'cluster-bus-port': int(cluster_port) if cluster_port else 10000 + int(port),
                        ^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '16380,,shard-id=72f90d37be9cc2b257b03b7000e6b98c4d4e6a62'
